### PR TITLE
Version using TronWeb as an external dependency

### PR DESCRIPTION
**Pull request by sullof**
In the current implementation, SunWeb requires `TronWeb` and `ethers.js` as dependencies. This makes it quite large. 

A typical dApp, most likely, must use TronWeb anyway to perform some operations. This will cause that the amount of code that they have to load in the browser becomes unsustainable because they are loading TronWeb two times, plus a separate ethers.js, etc.

Considering SunWeb characteristics, a TronWeb plugin is not really doable (sorry about suggesting that solution). However, an alternative approach exists: 
 1. load TronWeb as a separate package
 2. pass the TronWeb class to SunWeb as a parameter

In this case, the constructor becomes:

```
constructor(TronWeb, mainOptions = false, sideOptions = false, mainGatewayAddress = false, sideGatewayAddress = false, sideChainId = false, privateKey = false) {
        SunWeb.TronWeb = TronWeb
        mainOptions = {...mainOptions, privateKey};
        sideOptions = {...sideOptions, privateKey};
        this.mainchain = new TronWeb(mainOptions);
        this.sidechain = new TronWeb(sideOptions);
        this.isAddress = this.mainchain.isAddress;
        this.utils = this.mainchain.utils;
        this.setMainGatewayAddress(mainGatewayAddress);
        this.setSideGatewayAddress(sideGatewayAddress);
        this.setChainId(sideChainId);
        this.injectPromise = this.utils.promiseInjector(this);
        this.validator = this.mainchain.trx.validator;

        const self = this;
        this.sidechain.trx.sign = (...args) => {
            return self.sign(...args);
        };
        this.sidechain.trx.multiSign = (...args) => {
            return self.multiSign(...args);
        };
    }
```
Despite the saving in size, this way SunWeb would work exactly as it works now, with the advantage that if TronWeb evolves, SunWeb evolves automatically without needing any update in the library.

An even better approach would be if the user defines `mainchain` and `sidechain` outside and pass the two TronWeb instances to SunWeb when it constructs the sunWeb instance. This would make SunWeb compatible with TronLink and other wallets because the wallets would manage the TronWeb instances as usual. In this case, the constructor would become something like:
```
    constructor(mainchain = false, sidechain = false, mainGatewayAddress = false, sideGatewayAddress = false, sideChainId = false) {
        this.mainchain = mainchain;
        this.sidechain = sidechain;
        this.isAddress = this.mainchain.isAddress;
        this.utils = this.mainchain.utils;
        this.setMainGatewayAddress(mainGatewayAddress);
        this.setSideGatewayAddress(sideGatewayAddress);
        this.setChainId(sideChainId);
        this.injectPromise = this.utils.promiseInjector(this);
        this.validator = this.mainchain.trx.validator;

        const self = this;
        this.sidechain.trx.sign = (...args) => {
            return self.sign(...args);
        };
        this.sidechain.trx.multiSign = (...args) => {
            return self.multiSign(...args);
        };
    }
```
In this case, the `sha256()` in `signTransation` instead than being executed as `SunWeb.TronWeb.utils.ethersUtils.sha256()` would be `this.mainchain.utils.ethersUtils.sha256`.

I would prefer this second approach, but the first (in this PR) reaches, anyway, the goal of reducing the amount of code that a dApp using at the same time TronWeb and SunWeb has to load.

Since I didn't test it, I am not sure that this works as I expect. 
Consider it mostly as a guide. 

Of course, it introduces a breaking change because people has to use a different approach to instantiate the object.

What do you think?

### CODE REVIEW

**Comment by summertanh** [comment]
@sullof Thanks for your great advice. I think we can take the second approach.

**Comment by sullof** [comment]
Next week, I will improve the TronWeb plugin interface. That would provide the ideal approach because that would be fully compatible with any external wallet, like TronLink, without requiring TronLink to do anything.

**Comment by summertanh** [comment]
> Next week, I will improve the TronWeb plugin interface. That would provide the ideal approach because that would be fully compatible with any external wallet, like TronLink, without requiring TronLink to do anything.

**Comment by summertanh** [comment]
@sullof You've done with exporting the sha256 method of etherUtils in tronweb, right? That is to say, users who want to use the sunweb, they just need to install the latest version 2.7.2 of tronweb. and take the second approach mentioned above.

**Comment by sullof** [comment]
> users who want to use the sunweb, they just need to install the latest version 2.7.2 of tronweb. and take the second approach mentioned above.

Yes.

**Comment by summertanh** [comment]
have published in npm registry. see sunweb v1.0.8

**Pull request closed without merging**
