### PR TITLE
 add proposal ALLOW_DAPP_152(1000013)

### PR DESCRIPTION
**Pull request by Lredhdx**
add proposal ALLOW_DAPP_152(1000013)

### CODE REVIEW

**Review by taihaofu — APPROVED** [review]

**Review by MastaBook — COMMENTED** [review]
TLLJfLK1VdjieYj9xEmZZjV24pVN3WKQ5q

**Review by pablo6116 — COMMENTED** [review]
https://github.com/tronprotocol/sun-network/pull/300#issue-478400240

**Review by KimJi55 — COMMENTED** [review]
Review

**Comment by pejman319** [comment]
hi

**Comment by Mirage1348** [comment]
>  add proposal ALLOW_DAPP_152(1000013)

**Pull request merged**
